### PR TITLE
Add functions for virtual Interfaces and list nics

### PR DESCRIPTION
**Pull request by anmoel**

### CODE REVIEW

**Comment by alvaroaleman** [comment]
@anmoel @fkollmann Is there anything that blocks the integration of this PR?

**Comment by fkollmann** [comment]
> @anmoel @fkollmann Is there anything that blocks the integration of this PR?

HI, thanks for the reminder. This one slipped my mind. I will review it next week. Best Regards, Felix

**Comment by fkollmann** [comment]
Sry it took so long. Back in the office, now. Currently looking into it...

**Comment by fkollmann** [comment]
Manually integrated

**Comment by fkollmann** [comment]
@anmoel Thanks for the patch! I improved the error handling of the library as I got some incompatibilities. I also activated the windows support. And I renamed the NIC stuff to NetworkInterface and VirtInt to VirtualInterface to keep things more readable to non-admins.

**Pull request closed without merging**
